PACKAGE="github.com/bahadrix/linesink"
BASE_FILE_NAME = "linesink"
VERSION := "0.1.0" #$(shell git describe --tags)
BUILD := "$(shell git rev-parse --short HEAD)"
LDFLAGS=-ldflags "-X=main.Version=$(VERSION) -X=main.Build=$(BUILD)"

DIR := ${CURDIR}
BUILD_DIR = $(DIR)/build

add-version:
	@echo Embedding version
	@echo "package cmd" > cmd/version.go
	@echo "// Autogenerated file, do not edit" >> cmd/version.go
	@echo 'var AppVersion = $(VERSION)' >> cmd/version.go
	@echo 'var AppBuild = $(BUILD)' >> cmd/version.go


install-deps:
	@echo "Getting dependencies"
	@go get -v -t ./...

test: install-deps
	go test -v -coverprofile=coverage.txt -covermode=atomic ./...

lint:
	@golint ./...

pre-build:
	@mkdir -p build

clean:
	@rm -rf build
	-@go clean

build: add-version pre-build install-deps
	@echo "Building"
	@go build -o ./build/$(BASE_FILE_NAME) $(LDFLAGS) $(PACKAGE)
	@echo "Done"

check-docker:
	@echo Checking docker installation
	@docker --version

docker-build-amd64: check-docker pre-build
	@docker run \
		--rm \
		-v $(DIR):/go/src/$(PACKAGE) \
		-v $(BUILD_DIR):/go/bin \
		-e GOARCH=amd64 \
		-it golang:buster \
		/bin/bash -c "cd /go/src/$(PACKAGE); make build"


